name: WakaTime Stats

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch: # allows manual trigger

jobs:
  update-readme:
    name: Update README with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.1.5
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
